# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b7f71100f9735e97b3dea164815a34227384614fb723b771acc79e487166732ae8882fa98ffa1a5d3d27eab9f5a908faddde59e6ce4d57eec62b4fdbe639125

test:
  secret_key_base: 7b9a5ef45a0b7de192cbac7e07ace593fe70d90b4bfd3166e2c99c399e7d0222ee99e567670d688d666bb122dcbe53f817a665ee98834983047a4f6507cb1c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
